{% set name = "jupytercad-freecad" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupytercad_freecad-{{ version }}.tar.gz
  sha256: 0ec7a83c81fda6bfec0b641aa6a87d5339a96eec6b7a2d1a735714f7244ad559

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - yarn
    - jupyterlab >=4,<5
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2
  run:
    - python >=3.8
    - jupyter_ydoc >=1.1,<2
    - y-py >=0.6,<0.7
    - jupytercad_core >=1,<2
    - freecad

test:
  imports:
    - jupytercad_freecad
  requires:
    - pip
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-freecad/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-freecad\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupytercad/jupytercad-freecad
  summary: 'JupyterCAD plugin adding support for .fcstd files'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/jupytercad/jupytercad-freecad

extra:
  recipe-maintainers:
    - martinRenou
    - trungleduc
